### PR TITLE
New toolchain support

### PR DESCRIPTION
**Pull request by uyjulian**
Add support for compiling with the new toolchain.  
The old toolchain can still be used for regression testing.

### CODE REVIEW

**Comment by Invictaz** [comment]
@uyjulian thanks! Would you be able to make this build upto standard with the fixes of: https://github.com/Rinnegatamante/DaedalusX64-vitaGL

**Comment by uyjulian** [comment]
No, that is not the purpose of this Pull Request.

**Comment by Invictaz** [comment]
@uyjulian I know, I'm not stupid. But in general? Because there is no issue tracker on your Git...

**Comment by uyjulian** [comment]
I'm not planning to do it myself any time soon.

**Comment by belek666** [comment]
Thanks ;)

**Comment by uyjulian** [comment]
No problem

**Pull request merged**
